// Template mail is 144 of the 280 live emails since 01-Aug. Every subject below is a real
// SHAPE from that queue with the names replaced; no real child or staff name appears.
import { describe, it, expect } from 'vitest';
import { machineFamily } from '../core/machine-mail';
import { rulesClassifier } from '../core/classify';
import { planIngest } from '../core/ingest';

const cat = (subject: string, body = '') =>
  rulesClassifier.classify({ subject, body }).category;

describe('one template shape gets exactly one answer', () => {
  it('files every exit pass under attendance, whatever the grade contains', () => {
    // The live defect: this identical shape was filed transport 56 times and leave-medical 24
    // times, because the grade and section text happened to differ.
    const shapes = [
      'Student Exit Pass - New Form filled for Kavya Menon (Grade 4 - Harmony) (FSK2099001)',
      'Student Exit Pass - New Form filled for Rehan Qureshi (Junior KG - Red) (FWGS2099002)',
      'Student Exit Pass - New Form filled for Aditi Rao (Grade 9 - Sagacity) (FSK2099003)',
    ];
    expect(shapes.map(s => cat(s))).toEqual(['leave-medical', 'leave-medical', 'leave-medical']);
  });

  it('files a sickbay notice as medical, not transport', () => {
    expect(cat('Kavya Menon has visited sickbay.')).toBe('leave-medical');
  });

  it('files early-in and late-out approvals as attendance', () => {
    expect(cat('EarlyIn Kavya Menon: Approved and Notified')).toBe('leave-medical');
    expect(cat('Re: LateOut Rehan Qureshi')).toBe('leave-medical');
  });

  it('does not treat the school paying a supplier as a fees enquiry', () => {
    expect(cat('PAYMENT FROM FOUNTAINHEAD SCHOOL TO ACME SUPPLIES - DOMNEFT12345 - 6789'))
      .toBe('not-a-request');
  });

  it('files a calendar invitation as a meeting', () => {
    expect(cat('Invitation: Parent meeting (Grade 4) @ Mon Sep 7, 2026 9:00am')).toBe('meetings');
  });

  it('files the daily missed-call report as plumbing', () => {
    expect(cat('Daily Misscall Report of 2026-08-26')).toBe('systems');
  });

  it('files a Workspace notice as noise', () => {
    expect(cat('Security alert')).toBe('not-a-request');
    expect(cat('A Person has left the team of Fountainhead School')).toBe('not-a-request');
  });
});

describe('safeguarding still outranks every template', () => {
  it('does not let an exit-pass subject bury a safety allegation in the body', () => {
    const s = rulesClassifier.classify({
      subject: 'Student Exit Pass - New Form filled for Kavya Menon (Grade 4)',
      body: 'She was left alone at the gate for forty minutes and nobody was there to receive her.',
    });
    expect(s.category).toBe('child-safety');
    expect(s.isSafeguarding).toBe(true);
  });
});

describe('mail a person actually wrote is left to the rest of the classifier', () => {
  it('returns no family for ordinary prose', () => {
    expect(machineFamily('Requesting for sick leave.')).toBeNull();
    expect(machineFamily('Bus stop change for drop')).toBeNull();
    expect(machineFamily('')).toBeNull();
  });

  it('matches on the SUBJECT only, so a quoted notice does not hijack a real question', () => {
    // A parent forwarding an exit-pass notice to ask a question about it is a question.
    expect(machineFamily('Why did I get this?')).toBeNull();
    expect(cat('Why did I get this?', 'Fwd: Student Exit Pass - New Form filled for my daughter'))
      .not.toBe('leave-medical');
  });
});

describe('template mail never enters the working queue (VK, 27-Aug-2026)', () => {
  // "no they should not... front desk can refer to the app if at all they need to refer to
  // this information." Parked means: no response clock, out of every staff list, still on the
  // record and still listed on /mailbox.
  const ingest = (subject: string) => planIngest(
    {
      messageId: `m-${subject.length}`, threadId: `t-${subject.length}`,
      from: { name: 'School Forms', email: 'forms@fsksurat.in' },
      recipients: ['frontdesk@fsksurat.in'],
      subject, body: 'Generated by the form.', sentAt: new Date('2026-08-20T04:00:00Z'),
      channel: 'email',
    } as never,
    {
      seenMessageIds: new Set(), threadToRequest: new Map(),
      aliasToCampus: new Map([['frontdesk@fsksurat.in', 'fsk']]), fallbackCampus: 'fsk',
      classifierName: 'rules',
    } as never,
  );

  it('parks an exit pass and gives it no response clock', () => {
    const d = ingest('Student Exit Pass - New Form filled for Kavya Menon (Grade 4)');
    expect(d.action).toBe('create');
    if (d.action !== 'create') return;
    expect(d.fields.status).toBe('not_a_request');
    expect(d.fields.slaDueAt).toBeNull();
    expect(d.fields.isAutomated).toBe(true);
  });

  it('parks a sickbay notice', () => {
    const d = ingest('Kavya Menon has visited sickbay.');
    if (d.action !== 'create') throw new Error('expected create');
    expect(d.fields.status).toBe('not_a_request');
  });

  it('keeps the real category so the record still says what it is', () => {
    // Flattened to 'not-a-request' it would be out of the queue but also unfindable, which is
    // the half of VK's instruction that is easy to miss.
    const d = ingest('Kavya Menon has visited sickbay.');
    if (d.action !== 'create') throw new Error('expected create');
    expect(d.fields.category).toBe('leave-medical');
  });

  it('still lets a parent writing ordinary prose into the queue', () => {
    const d = ingest('Requesting for sick leave.');
    if (d.action !== 'create') throw new Error('expected create');
    expect(d.fields.status).toBe('unfiled');
    expect(d.fields.slaDueAt).not.toBeNull();
  });
});

describe('the safeguarding vocabulary does not over-fire on school mail', () => {
  // The rescue pass re-reads mail an earlier classifier set aside, so a loose pattern here
  // would drag marketing back into the queue at critical urgency. Measured against 284 real
  // production records before shipping: it matched 2, both genuine. These lock in the stems
  // that make that true.
  const safety = (s: string) => rulesClassifier.classify({ subject: s, body: '' }).category;

  it('does not fire on a mock exam', () => {
    expect(safety('Mock exam timetable for Grade 10')).not.toBe('child-safety');
    expect(safety('Mock test results are out')).not.toBe('child-safety');
  });

  it('does not fire on "ridiculous", which is what complaints call things', () => {
    expect(safety('This is a ridiculous amount of homework')).not.toBe('child-safety');
  });

  it('still fires on how a parent actually describes humiliation', () => {
    expect(safety('My daughter was mocked by a teacher')).toBe('child-safety');
    expect(safety('She was humiliated in front of the class')).toBe('child-safety');
    expect(safety('The child is traumatized')).toBe('child-safety');
  });

  it('still fires on the policy vocabulary, mid-word', () => {
    // No trailing \b after "harass" on purpose — the real corpus said "Harassment".
    expect(safety('Harassment complaint')).toBe('child-safety');
  });
});
