// core/machine-mail.ts — the mail nobody wrote.
//
// Measured on the live queue, 26-Aug-2026: 144 of 280 emails since 01-Aug are generated by a
// form, a calendar, a bank or Google — not typed by a parent. That is more than half the desk's
// inbox, and every family of it has exactly ONE right answer, because the subject line is
// assembled by a template.
//
// Both classifiers were getting them wrong, in opposite ways:
//
//   * RULES scattered them. The single shape "Student Exit Pass - New Form filled for <name>"
//     appeared 80 times and was filed `transport` 56 times and `leave-medical` 24 times — the
//     same email, two categories, depending on which words the child's grade happened to
//     contain. All 20 "<name> has visited sickbay." notices were filed `transport`.
//   * THE MODEL was inconsistent. Asked about the same exit-pass shape it answered
//     `leave-medical` for six and `not-a-request` for nine. Fluent both times.
//
// Neither failure is a judgement problem, so neither wants a judgement engine. A template
// deserves a template: match the shape, return the answer, be right every time. What is left
// over is human prose, which is where judgement is actually worth paying for.
//
// PURE. Subject-anchored on purpose — a body can quote anything, including a forwarded copy of
// one of these notices inside a real parent's question about it.

import type { Urgency } from './taxonomy';

export interface MachineFamily {
  /** Stable id, used in the reason shown to the desk and in tests. */
  key: string;
  re: RegExp;
  category: string;
  urgency: Urgency;
  /** Written for a desk assistant reading it beside the suggestion. */
  reason: string;
}

export const MACHINE_FAMILIES: MachineFamily[] = [
  {
    // 80 in the live queue — the single largest family of mail the desk receives.
    // NOT 'not-a-request': a child is leaving early and somebody at the desk has to release
    // them. It is automated, but it is not noise, and burying it would hide real work.
    key: 'exit-pass',
    re: /\bexit pass\b|\bstudent exit pass\b/i,
    category: 'leave-medical',
    urgency: 'normal',
    reason: 'Automated exit-pass form — a child is leaving early. Filed under attendance.',
  },
  {
    // 20 in the live queue, every one previously filed as transport.
    key: 'sickbay',
    re: /\bhas visited sickbay\b|\bsickbay (visit|notification)\b/i,
    category: 'leave-medical',
    urgency: 'normal',
    reason: 'Automated sickbay notice — a health record, not a transport matter.',
  },
  {
    // 13 in the live queue. Early arrival / late departure approvals: attendance, not buses.
    key: 'early-late',
    re: /^\s*(re:\s*)?(earlyin|lateout)\b/i,
    category: 'leave-medical',
    urgency: 'normal',
    reason: 'Automated early-in / late-out approval — an attendance record.',
  },
  {
    // 12 in the live queue, all filed `fees` because of the word PAYMENT. These are the
    // school's own bank advising it that IT paid a supplier. No parent, no request, no action.
    key: 'vendor-payment-advice',
    re: /^\s*payment from fountainhead school to\b/i,
    category: 'not-a-request',
    urgency: 'low',
    reason: 'Bank advice for a payment the school made to a supplier. Nothing for the desk.',
  },
  {
    // Google Calendar. Previously landed in leave-medical because invitations mention times.
    key: 'calendar-invite',
    re: /^\s*(updated invitation|invitation|accepted:|declined:|canceled event|cancelled event)\b/i,
    category: 'meetings',
    urgency: 'low',
    reason: 'A calendar invitation, not a message.',
  },
  {
    // The desk's own missed-call report. There is already an explosion path that turns each
    // row into a slip; the report email itself is plumbing.
    key: 'missed-call-report',
    re: /\bmiss?call report\b|\bmissed[- ]call report\b|\bdaily misscall\b/i,
    category: 'systems',
    urgency: 'low',
    reason: 'The daily missed-call report. Each call inside it is captured separately.',
  },
  {
    // Google Workspace: sign-in alerts, "X has left the team", sharing notices.
    key: 'workspace-notice',
    re: /^\s*(security alert|critical security alert)\b|\bhas left the team of\b|\bhas joined the team of\b/i,
    category: 'not-a-request',
    urgency: 'low',
    reason: 'An automated Google Workspace notice.',
  },
];

/**
 * Identify template mail from its SUBJECT.
 *
 * Returns null for anything a person actually wrote — which is the answer the rest of the
 * classifier, and the model, should be spending their effort on.
 */
export function machineFamily(subject: string | null | undefined): MachineFamily | null {
  const s = subject ?? '';
  if (!s.trim()) return null;
  return MACHINE_FAMILIES.find(f => f.re.test(s)) ?? null;
}
