/* AUTO-GENERATED by scripts/generate_tokens.py - do not edit by hand. */
/**
 * Fountainhead Design System — Tailwind preset (Tailwind 3.4+).
 * Usage in the consuming app's tailwind config:
 *   presets: [require('@fountainhead/design-system/tailwind-preset')]
 * Requires the design tokens CSS (css/tokens.css) to be loaded for the
 * theme-aware (var-based) colours, and next/font vars --font-montserrat /
 * --font-nunito for the font families.
 */
module.exports = {
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
      "fh-blue": {
            "50": "#E6EFF6",
            "100": "#CCDEEE",
            "200": "#A8C7E2",
            "300": "#80ADD4",
            "400": "#5793C7",
            "500": "#2E79B9",
            "600": "#005BAA",
            "700": "#004C8F",
            "800": "#003E74",
            "900": "#002747"
      },
      "fh-red": {
            "50": "#F8EAEA",
            "100": "#F1D4D5",
            "200": "#E7B6B8",
            "300": "#DC9497",
            "400": "#D07276",
            "500": "#C55054",
            "600": "#B8292F",
            "700": "#9E2227",
            "800": "#7D1B1F",
            "900": "#5C1417"
      },
      "fh-yellow": {
            "50": "#FBEBB0",
            "100": "#F8E28C",
            "200": "#F6D867",
            "300": "#F4CF42",
            "400": "#F2C418",
            "500": "#DAB015",
            "600": "#C29C13",
            "700": "#AA8810",
            "800": "#95760E",
            "900": "#83680C"
      },
      "fh-green": {
            "50": "#E9F3ED",
            "100": "#D2E8DB",
            "200": "#B3D7C2",
            "300": "#8FC4A6",
            "400": "#6BB289",
            "500": "#479F6C",
            "600": "#1F8A4C",
            "700": "#1B7C44",
            "800": "#186E3D",
            "900": "#146035"
      },
      "fh-neutral": {
            "0": "#FFFFFF",
            "50": "#F6F7F9",
            "100": "#ECEEF1",
            "200": "#DCE0E5",
            "300": "#C5CBD3",
            "400": "#9BA4AF",
            "500": "#6E7884",
            "600": "#545C68",
            "700": "#3E454E",
            "800": "#2A2F37",
            "900": "#181C22",
            "950": "#0F1216"
      },
      "background": "var(--fh-color-bg)",
      "surface": {
            "DEFAULT": "var(--fh-color-surface)",
            "raised": "var(--fh-color-surface-raised)",
            "sunken": "var(--fh-color-surface-sunken)"
      },
      "foreground": "var(--fh-color-text)",
      "muted": "var(--fh-color-text-muted)",
      "subtle": "var(--fh-color-text-subtle)",
      "inverse": "var(--fh-color-text-inverse)",
      "border": {
            "DEFAULT": "var(--fh-color-border)",
            "strong": "var(--fh-color-border-strong)"
      },
      "ring": "var(--fh-color-focus)",
      "link": "var(--fh-color-text-link)",
      "primary": {
            "DEFAULT": "var(--fh-color-primary)",
            "foreground": "var(--fh-color-primary-fg)",
            "subtle": "var(--fh-color-primary-subtle)",
            "hover": "var(--fh-color-primary-hover)"
      },
      "secondary": {
            "DEFAULT": "var(--fh-color-secondary)",
            "foreground": "var(--fh-color-secondary-fg)",
            "subtle": "var(--fh-color-secondary-subtle)",
            "hover": "var(--fh-color-secondary-hover)"
      },
      "accent": {
            "DEFAULT": "var(--fh-color-accent)",
            "foreground": "var(--fh-color-accent-fg)",
            "subtle": "var(--fh-color-accent-subtle)",
            "hover": "var(--fh-color-accent-hover)"
      },
      "success": {
            "DEFAULT": "var(--fh-color-success)",
            "foreground": "var(--fh-color-success-fg)",
            "subtle": "var(--fh-color-success-subtle)",
            "hover": "var(--fh-color-success-hover)",
            "soft": "var(--fh-color-success-soft)"
      },
      "warning": {
            "DEFAULT": "var(--fh-color-warning)",
            "foreground": "var(--fh-color-warning-fg)",
            "subtle": "var(--fh-color-warning-subtle)",
            "hover": "var(--fh-color-warning-hover)",
            "soft": "var(--fh-color-warning-soft)"
      },
      "danger": {
            "DEFAULT": "var(--fh-color-danger)",
            "foreground": "var(--fh-color-danger-fg)",
            "subtle": "var(--fh-color-danger-subtle)",
            "hover": "var(--fh-color-danger-hover)",
            "soft": "var(--fh-color-danger-soft)"
      },
      "info": {
            "DEFAULT": "var(--fh-color-info)",
            "foreground": "var(--fh-color-info-fg)",
            "subtle": "var(--fh-color-info-subtle)"
      },
      "diverging": {
            "neg-strong": "var(--fh-color-diverging-neg-strong)",
            "neg": "var(--fh-color-diverging-neg)",
            "neutral": "var(--fh-color-diverging-neutral)",
            "pos": "var(--fh-color-diverging-pos)",
            "pos-strong": "var(--fh-color-diverging-pos-strong)"
      },
      "scale-quality": {
            "1": "var(--fh-color-scale-quality-1)",
            "2": "var(--fh-color-scale-quality-2)",
            "3": "var(--fh-color-scale-quality-3)",
            "4": "var(--fh-color-scale-quality-4)",
            "5": "var(--fh-color-scale-quality-5)",
            "6": "var(--fh-color-scale-quality-6)",
            "none": "var(--fh-color-scale-quality-none)"
      },
      "chart": {
            "reference": "var(--fh-color-chart-reference)",
            "grid": "var(--fh-color-chart-grid)"
      }
},
      borderColor: { DEFAULT: 'var(--fh-color-border)' },
      ringColor: { DEFAULT: 'var(--fh-color-focus)' },
      fontFamily: {
      "heading": [
            "var(--font-montserrat)",
            "Montserrat",
            "system-ui",
            "sans-serif"
      ],
      "body": [
            "var(--font-nunito)",
            "Nunito",
            "system-ui",
            "sans-serif"
      ],
      "sans": [
            "var(--font-nunito)",
            "Nunito",
            "system-ui",
            "sans-serif"
      ],
      "ui": [
            "Inter",
            "system-ui",
            "-apple-system",
            "Segoe UI",
            "Roboto",
            "sans-serif"
      ],
      "mono": [
            "ui-monospace",
            "Consolas",
            "monospace"
      ]
},
      fontSize: {
      "xs": "0.75rem",
      "sm": "0.875rem",
      "base": "1rem",
      "lg": "1.125rem",
      "xl": "1.3125rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "2.625rem",
      "6xl": "3.375rem"
},
      borderRadius: {
      "none": "0",
      "xs": "4px",
      "sm": "6px",
      "DEFAULT": "8px",
      "md": "8px",
      "lg": "12px",
      "xl": "16px",
      "2xl": "24px",
      "full": "9999px"
},
      boxShadow: {
      "fh-xs": "var(--fh-shadow-xs)",
      "fh-sm": "var(--fh-shadow-sm)",
      "fh-md": "var(--fh-shadow-md)",
      "fh-lg": "var(--fh-shadow-lg)",
      "fh-xl": "var(--fh-shadow-xl)"
},
    },
  },
};
